### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by engor** [filbabic/FlexibleAdapter#2]
You have a method
```
public int getItemViewType(int position) {
    return getItem(position) != null ? getItem(position).getLayout() : R.layout.default_layout;
}
```
My suggestions:
1. Initialize `R.layout.default_layout` via adapter's constructor.
2. (Maybe) Store `getItem(position)` in a local variable to avoid list search twice (check the same in other methods). Although isn't actual for arraylists.

**Comment by filbabic** [comment]
Thanks for pointing out! I've fixed the unnecessary item queries. The second part I'm not sure I'll include in the library, as it might force people who do not need a default layout, to provide something(maybe not safe), just to create an adapter. However I've made it so that the default_layout is just a 0dp height View, to minimize the cost of it's inflation. Also if you make a R.layout.default_layout in your application's res files, the Adapter should be overridden in a way that it uses your default_layout resource, rather than mine :)
